name: zqqkkz

on:
  workflow_dispatch:
  schedule:
      - cron: '0 0,10 * * *'
jobs:
  build1:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【zqqkkz】'
        run: |
          node Task/zqqkkz.js
